export default {
  welcome: 'Welcome',
  tag: 'Tag',
  postDate: 'PostDate',
  postTime: 'PostTime',
  ref: 'Ref',
  filetype: 'FileType',
  filesize: 'FileSize',
  ip: 'IP',
  sha256: 'SHA256',
  copy: 'Copy',
  location: 'Location',
  uploadDate: 'UploadDate',
  uploadTime: 'UploadTime',
  assetTitle: 'Asset Description',
  enter: 'Enter',
  remove: 'Remove',
  edit: 'Edit',
  add: 'Add',
  back: 'Back',
  raw: 'Raw',
  advanced: 'Advanced',
  basic: 'Basic',
  save: 'Save',
  cancel: 'Cancel',
  assetsMeta: 'Assets Meta',
  longtext: 'Long Text',
  shorttext: 'Short Text',
  photoarchive: 'Photo Archive',
  filearchive: 'File Archive',
  editing: 'Editing',
}
